/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevHotjarInsightsRouteImport } from './routes/dev/hotjar-insights'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevHotjarInsightsRoute = DevHotjarInsightsRouteImport.update({
  id: '/dev/hotjar-insights',
  path: '/dev/hotjar-insights',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev/hotjar-insights': typeof DevHotjarInsightsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev/hotjar-insights': typeof DevHotjarInsightsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev/hotjar-insights': typeof DevHotjarInsightsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dev/hotjar-insights'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dev/hotjar-insights'
  id: '__root__' | '/' | '/dev/hotjar-insights'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevHotjarInsightsRoute: typeof DevHotjarInsightsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/hotjar-insights': {
      id: '/dev/hotjar-insights'
      path: '/dev/hotjar-insights'
      fullPath: '/dev/hotjar-insights'
      preLoaderRoute: typeof DevHotjarInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevHotjarInsightsRoute: DevHotjarInsightsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
